services:
  backend:
    build: NoteApplication
    environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - DATABASE_URL=jdbc:postgresql://postgres-database:5432/backend
            - DATABASE_DDL=update
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres-database
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backend
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

